name: build adocs

on:
  push:
    branches:
      - feat/github-action
jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    name: generate schema docs
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docs
        id: adocbuild
        uses: tonynv/asciidoctor-action@master
        with:
          program: "./generate_schema_docs.sh -v V1.2.3"

      - name: Copy src files
        run: cp src/*.csv dist/

      - name: Build index page
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: cd ./github && sudo ./generate_index.sh -r "$GITHUB_REPOSITORY"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist