name: Broken Link Check
on:
  push:
    branches:
      - main

  schedule:
    - cron: 0 0 1 * * # run monthly

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Sleep to allow build actions to complete
        run: sleep 30s
        shell: bash

      - name: Full Schema Link Check
        if: always()
        id: link-report-full-schema
        uses: jodyhoonstarr/link-checker@master
        with:
          url: 'https://ledapplications.github.io/lehd-schema/lehd_public_use_schema.html'
          honorRobotExclusions: true
          ignorePatterns: ''
          recursiveLinks: false

      - name: CSV Naming Link Check
        if: always()
        id: link-report-csv-naming
        uses: jodyhoonstarr/link-checker@master
        with:
          url: 'https://ledapplications.github.io/lehd-schema/lehd_csv_naming.html'
          honorRobotExclusions: true
          ignorePatterns: ''
          recursiveLinks: false

      - name: Shapefiles Link Check
        if: always()
        id: link-report-shapefiles
        uses: jodyhoonstarr/link-checker@master
        with:
          url: 'https://ledapplications.github.io/lehd-schema/lehd_shapefiles.html'
          honorRobotExclusions: true
          ignorePatterns: 'https://ledapplications.github.io/lehd-schema/lehd_shp_*.zip'
          recursiveLinks: false
