name: Broken Link Check

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Sleep to allow build actions to complete
        run: sleep 60s
        shell: bash

      - name: Full Schema Link Check
        if: always()
        id: link-report-full-schema
        uses: jodyhoonstarr/link-checker@master
        with:
          url: 'https://ledapplications.github.io/lehd-schema/lehd_public_use_schema.html'
          honorRobotExclusions: true
          ignorePatterns: ''
          recursiveLinks: false

      - name: CSV Naming Link Check
        if: always()
        id: link-report-csv-naming
        uses: jodyhoonstarr/link-checker@master
        with:
          url: 'https://ledapplications.github.io/lehd-schema/lehd_csv_naming.html'
          honorRobotExclusions: true
          ignorePatterns: ''
          recursiveLinks: false

      - name: Shapefiles Link Check
        if: always()
        id: link-report-shapefiles
        uses: jodyhoonstarr/link-checker@master
        with:
          url: 'https://ledapplications.github.io/lehd-schema/lehd_shapefiles.html'
          honorRobotExclusions: true
          ignorePatterns: 'https://ledapplications.github.io/lehd-schema/lehd_shp_*.zip,https://www.loc.gov/preservation/digital/formats/fdd/fdd000280.shtml'
          recursiveLinks: false
